### ISSUE TITLE
Change # stationary in Collateral

### ISSUE THREAD

**Issue by Mullebrouck** [vasco3/CareForDesigning#16]
Is it possible to show me where I can change the #stationary into Collateral? I did it already at the navigation bar, but I couldn't find it where else I would have to change it. And I didn't want to mess up the code :)

**Comment by vasco3** [comment]
do you still need help with this?

**Comment by Mullebrouck** [comment]
yes, I changed only the stationary tag in the navigation bar, but I didn't find where I need to adjust it in the #stationary

**Comment by vasco3** [comment]
oh so you just need to change the word **stationary** for **collateral** in the `data/CategoryData.js`

**Comment by Mullebrouck** [comment]
Thank you 
:+1:
